name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Install server dependencies
        working-directory: ./Code/server
        run: npm install

      - name: Run server tests
        working-directory: ./Code/server
        run: npm test